#!/usr/bin/env python3
"""Define the authored 76-song expansion for the Rise & Grind audio catalog."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ExpansionTrack:
    """Store one expansion track's public metadata and compact performed lyrics."""

    title: str
    band: str
    genre_name: str
    genre_description: str
    lyrics: tuple[str, ...]
    female_slut_pride: bool = False


EXPANSION_TRACKS: tuple[ExpansionTrack, ...] = (
    ExpansionTrack(
        "Bed Tax Massacre",
        "Clockjaw Verdict",
        "Thrash Metal",
        "Merciless bay-area-style velocity, serrated downpicking, double-kick artillery, and a barked gang hook.",
        (
            "Wake up, the mattress is charging you interest!",
            "Your daylight is dying while rivals get paid.",
            "Feet to the floor, put the riff in your backbone.",
            "No cash in the sheets—move your ass and collect!",
        ),
    ),
    ExpansionTrack(
        "Snooze Crusher",
        "Cinderblock Bonus",
        "Groove Metal",
        "Concrete-heavy syncopated guitars, piston kicks, and a chorus built to shake a phone off the nightstand.",
        (
            "Snooze is a hammer aimed straight at your future.",
            "You keep taking the hit and calling it rest.",
            "Stand up, lock in, make the morning your employee.",
            "Awake makes money; asleep makes excuses!",
        ),
    ),
    ExpansionTrack(
        "Corpse on Payroll",
        "Morgue Incentive",
        "Death Metal",
        "Blast-beat death metal with chainsaw tremolo, subterranean growls, and a grotesquely catchy wake-up refrain.",
        (
            "You look like a corpse with a calendar problem.",
            "The clock ate your alibi and spat out the bones.",
            "Rise from the bed, earn breath, earn money.",
            "The dead do not invoice—wake the fuck up!",
        ),
    ),
    ExpansionTrack(
        "Vertical or Broke",
        "Deadline Anatomy",
        "Metalcore",
        "Panic chords and screamed verses detonate into a skyscraping clean chorus and a floor-caving half-time drop.",
        (
            "Horizontal is broke; vertical gets dangerous.",
            "Your dream job cannot hear you snore.",
            "Open your eyes, take the day by the throat.",
            "Get vertical now—your future is awake!",
        ),
    ),
    ExpansionTrack(
        "Dragon of Direct Deposit",
        "Chrome Overtime",
        "Power Metal",
        "Ridiculous heroic speed metal with galloping drums, twin-guitar lightning, and a choir worshipping direct deposit.",
        (
            "Mount the dawn, payroll rider, the gold engine calls!",
            "No crown waits under a cowardly quilt.",
            "Raise your coffee, charge into commerce.",
            "Awake we conquer; awake we get paid!",
        ),
    ),
    ExpansionTrack(
        "Human Resource Error",
        "Piston Memo",
        "Industrial Metal",
        "Hydraulic riffs, factory alarms, steel percussion, and a distorted supervisor barking a hostile boot sequence.",
        (
            "Error: worker horizontal, revenue offline.",
            "Remove blanket obstruction; enable spine.",
            "Boot coffee, load ambition, execute daylight.",
            "Human resource awake—profit system armed!",
        ),
    ),
    ExpansionTrack(
        "Evict the Pillow",
        "Rent Strike Teeth",
        "Hardcore Punk",
        "A ninety-second basement set crushed into a furious loop of power chords, snare cracks, and eviction-notice gang vocals.",
        (
            "Evict the pillow, it never paid rent!",
            "Kick out the blanket, it stole your whole shift!",
            "Your friends are moving, your boss is awake.",
            "Get up, get loud, get fucking paid!",
        ),
    ),
    ExpansionTrack(
        "Circle Pit Clock-In",
        "Municipal Knife Party",
        "Crossover Thrash",
        "Skate-punk speed collides with thrash-metal bite and a circle-pit chant timed to the punch clock.",
        (
            "Clock in, circle up, shoulder-check the sunrise!",
            "You wasted enough life negotiating with sheets.",
            "Run the day until the day begs mercy.",
            "No snooze, no stall, no broke-ass morning!",
        ),
    ),
    ExpansionTrack(
        "Crust Before Comfort",
        "Ashtray Pension",
        "Crust Punk",
        "D-beat filth, blown speakers, rusted bass, and a hoarse communal howl against comfort and wasted daylight.",
        (
            "Comfort is a landlord with mold in its lungs.",
            "It keeps you asleep while the rich stay fed.",
            "Boots on, eyes open, steal back the morning.",
            "No gods, no snooze, no unpaid time!",
        ),
    ),
    ExpansionTrack(
        "Kickflip the Clock",
        "Payroll Halfpipe",
        "Skate Punk",
        "Breakneck skate punk with palm-muted sprints, airborne drums, and a sunny chorus yelling insults at the snooze button.",
        (
            "Kickflip the clock, grind rail the sunrise!",
            "Your bed is a poser and your snooze button sucks.",
            "Lace up, launch out, make the whole day watch.",
            "Awake is fast and fast gets paid!",
        ),
    ),
    ExpansionTrack(
        "Late Again, Genius",
        "Parking Lot Valedictorian",
        "Pop Punk",
        "Sugar-rush guitars, bratty nasal hooks, and drums sprinting like someone just remembered an eight o'clock shift.",
        (
            "Late again, genius, what a brilliant career plan.",
            "You dated your pillow and ghosted the day.",
            "Pull on your pants, sing loud, leave now.",
            "Being awake beats being sorry by noon!",
        ),
    ),
    ExpansionTrack(
        "Walk of Fame",
        "Consent Agenda",
        "Riot Grrrl",
        "Female-led riot grrrl with chainsaw chords, stomp-claps, and a gleefully vulgar consensual slut-pride gang chorus.",
        (
            "Wake up, sluts, the walk of shame is a victory lap!",
            "My choices are mine and my pleasure clocks in.",
            "Lipstick, consent, invoices, power.",
            "I own my body and I own this fucking morning!",
        ),
        True,
    ),
    ExpansionTrack(
        "Feedback for Breakfast",
        "The Exit Interviewers",
        "Post Hardcore",
        "Angular clean guitars collapse into screamed catharsis, octave chords, and a huge awake-is-better refrain.",
        (
            "Feedback for breakfast, panic for lunch.",
            "You cannot build a life from a recurring snooze.",
            "Cut the dream loose, let the daylight answer.",
            "Eyes open hurts; eyes open works!",
        ),
    ),
    ExpansionTrack(
        "Seven-Eighths to Work",
        "Spreadsheet Locust",
        "Mathcore",
        "Stop-start guitars in hostile odd meters, impossible drum accents, and screamed arithmetic for the chronically horizontal.",
        (
            "Count five, count seven, count every minute you burned.",
            "The mattress divided your courage by zero.",
            "Solve for shoes, coffee, motion, money.",
            "The answer is awake—show your fucking work!",
        ),
    ),
    ExpansionTrack(
        "Amphetamine Rooster",
        "Velvet Fire Code",
        "Noise Rock",
        "Sheet-metal guitar noise, lurching bass, blown-out drums, and a rooster scream fed through a broken megaphone.",
        (
            "The rooster ate lightning and learned your address.",
            "It brought feedback, invoices, and contempt.",
            "Wake up before the walls start billing you.",
            "Noise makes motion; motion makes money!",
        ),
    ),
    ExpansionTrack(
        "Flannel Foreclosure",
        "Mildew Executive",
        "Grunge Punk",
        "Fuzz-caked grunge riffs dragged at punk tempo, with a cracked vocal that sounds allergic to blankets and bosses.",
        (
            "Your flannel is ready, your rent is not.",
            "The ceiling knows every excuse by name.",
            "Roll out angry, stand up ugly.",
            "A bad awake day still pays better than sleep!",
        ),
    ),
    ExpansionTrack(
        "Pillow Talk Is Cheap",
        "Invoice Cipher",
        "Boom Bap",
        "Dusty drums, needle scratches, upright-bass menace, and a razor-clear emcee dismantling every sleepy excuse.",
        (
            "Pillow talk is cheap and your rent is expensive.",
            "Dreams need legs, deadlines, mileage, receipts.",
            "Brush off the dust, put the plan in the street.",
            "You cannot stack paper with your eyes shut!",
        ),
    ),
    ExpansionTrack(
        "Paid and Promiscuous",
        "Velvet Direct Deposit",
        "Trap",
        "Female-led volcanic trap with seismic 808s, razor hi-hats, and a consensual slut-pride hook dripping with financial swagger.",
        (
            "I wake up paid and promiscuous—both by my own design.",
            "My lovers ask nicely and my clients pay on time.",
            "Consent, cash, lashes, ambition.",
            "This grown slut runs the whole damn morning!",
        ),
        True,
    ),
    ExpansionTrack(
        "Tea Cold, Rent Hot",
        "Borough Alarm Unit",
        "Grime",
        "Icy square-wave bass, clipped drums, and a breathless UK emcee firing wake-up bars with zero wasted syllables.",
        (
            "Tea went cold but the rent stayed hot.",
            "You slept through chances the crew already got.",
            "Up now, trainers on, brain switched live.",
            "Daylight pays workers, not a duvet inside!",
        ),
    ),
    ExpansionTrack(
        "Blanket Opp Block",
        "Dawn Warrant",
        "Drill",
        "Sliding bass, sinister bells, clipped drill percussion, and an ice-cold warning directed exclusively at the bed.",
        (
            "Blanket is an opp and the pillow set you up.",
            "Clock on the wall says your alibi is done.",
            "Step out focused, make the block remember.",
            "Sleep got no motion and no money either!",
        ),
    ),
    ExpansionTrack(
        "Scream at the Balance",
        "Overdraft Moshpit",
        "Rage Rap",
        "Blown-out synths, clipping drums, and an arena of feral ad-libs attacking an overdraft before breakfast.",
        (
            "Wake! Wake! Scream at the balance!",
            "Broke feels louder when you sleep through the answer.",
            "Jump from the bed, punch holes in the schedule.",
            "Get up, get wild, get revenue now!",
        ),
    ),
    ExpansionTrack(
        "Alarm in the Trunk",
        "Breakfast Subwoofer",
        "Crunk",
        "Riotous call-and-response rap, trunk-rattling low end, handclaps, and a hook designed for shouting while finding pants.",
        (
            "What we do? Get up! What we make? Money!",
            "Where you at? Still in bed? That ain't funny!",
            "Throw the covers, stomp the floor.",
            "Whole house awake when the bass hits four!",
        ),
    ),
    ExpansionTrack(
        "Bass Before Breakfast",
        "South Beach Punchclock",
        "Miami Bass",
        "Rubbery sub-bass, electro claps, siren synths, and a shameless party chant that turns dawn into a parking-lot system test.",
        (
            "Bass before breakfast, feet before excuses.",
            "The sun brought heat and your bank brought notices.",
            "Shake off sleep, shake the room, shake the plan alive.",
            "Awake gets paid when the low end arrives!",
        ),
    ),
    ExpansionTrack(
        "Heels Before Emails",
        "Club Consent Committee",
        "Jersey Club",
        "Female-led Jersey club with bed-squeak kicks, chopped vocals, and a playful adult slut-pride chant built on explicit consent.",
        (
            "Heels before emails, consent before touch.",
            "I had fun last night and I still earn too much.",
            "Wake, bounce, choose, invoice.",
            "This slut owns sunrise and her schedule!",
        ),
        True,
    ),
    ExpansionTrack(
        "Graveyard Direct Deposit",
        "Cowbell Undertaker",
        "Phonk",
        "Distorted cowbells, tape-hiss menace, subterranean bass, and a grave-low flow cruising straight through dawn.",
        (
            "Graveyard bass but my eyes stay lit.",
            "You sleep like the coffin has benefits.",
            "Slide out the sheets, put the wheels on the hustle.",
            "Morning money needs an awake mind and muscle!",
        ),
    ),
    ExpansionTrack(
        "Cubicle Riot Signal",
        "Copier Guillotine",
        "Industrial Hip Hop",
        "Scrap-metal drums, distorted samples, and militant rap delivered like a mutiny over the office intercom.",
        (
            "Cubicle riot signal, fluorescent dawn.",
            "The copier is working while your pants are not on.",
            "Wake, organize, sabotage the delay.",
            "Take back your labor and bill for the day!",
        ),
    ),
    ExpansionTrack(
        "Kick Drum Eviction",
        "Concrete BPM",
        "Hard Techno",
        "Punishing warehouse kicks, metallic rumble, and a four-word command loop that feels like eviction by subwoofer.",
        (
            "Wake up. Stand up. Clock in. Cash out.",
            "The kick owns the room and the dawn owns the clock.",
            "No sleep in the warehouse of daylight.",
            "Move your ass on every brutal beat!",
        ),
    ),
    ExpansionTrack(
        "Consent at Sunrise",
        "Acid Matriarchy",
        "Acid Techno",
        "Female-led 303 squelch and warehouse drums underpin an adult, consensual slut-pride mantra with dominatrix poise.",
        (
            "Consent at sunrise, pleasure on my terms.",
            "I choose every lover and I choose what I earn.",
            "Acid, agency, awake, adored.",
            "This proud slut answers to nobody's alarm but hers!",
        ),
        True,
    ),
    ExpansionTrack(
        "Motor City Morning",
        "Assembly Line Oracle",
        "Detroit Techno",
        "Futurist chords, driving machine funk, and a cool spoken mantra riding an automated sunrise assembly line.",
        (
            "Motor City morning, machine heart awake.",
            "Every turning gear is a choice you can make.",
            "Leave the sleep loop, enter the live wire.",
            "Build the day clean, precise, and higher!",
        ),
    ),
    ExpansionTrack(
        "Nine Hundred BPM Notice",
        "Rotterdam Collections",
        "Gabber",
        "Distorted kick drums like collapsing buildings, hoover synths, and a mass chant serving a final notice to sleep.",
        (
            "Final notice! Sleep debt due!",
            "Nine hundred kicks coming straight through you!",
            "Wake the fuck up, demolish delay.",
            "Gabber gets moving and moving gets paid!",
        ),
    ),
    ExpansionTrack(
        "Reverse Bass Revenue",
        "Festival Payroll",
        "Hardstyle",
        "Towering supersaws, reverse-bass thunder, cinematic builds, and a stadium vocalist making income sound mythic.",
        (
            "Rise with the reverse bass, run with the light.",
            "Every sleeping minute is surrendered height.",
            "Hands up, eyes wide, let the whole crowd say:",
            "Awake is the power that carries the day!",
        ),
    ),
    ExpansionTrack(
        "Two-Step to the Timesheet",
        "Amen Break Benefits",
        "Drum and Bass",
        "Knife-edge breakbeats, roaring reese bass, and a rapid emcee sprinting through a timesheet at 174 BPM.",
        (
            "Two-step to the timesheet, quick feet, no sleep.",
            "Minutes get expensive when the deadlines creep.",
            "Eyes up, ride breaks, make the whole plan land.",
            "Daylight moves fast—better move on command!",
        ),
    ),
    ExpansionTrack(
        "Slut Mode Boot Sequence",
        "Glitch Consent",
        "Breakcore",
        "Female-led breakcore shreds Amen breaks beneath a hyperactive, consensual adult slut-pride boot sequence.",
        (
            "Boot sequence: slut mode, adult, awake, consenting.",
            "My body is mine; my desire is not pending.",
            "Break the beat, not my boundaries.",
            "I fuck, I work, I win the morning!",
        ),
        True,
    ),
    ExpansionTrack(
        "Wobble Out of Bed",
        "Subsidized Earthquake",
        "Dubstep",
        "Monstrous talking bass, stomping half-time drums, and a pre-drop whisper that turns into a furniture-moving command.",
        (
            "Your bed says stay; the bass says absolutely not.",
            "The clock is a fuse and the drop is hot.",
            "Three, two, one—wobble out of bed.",
            "Shake loose the sleep and go get bread!",
        ),
    ),
    ExpansionTrack(
        "Quarterly Drop",
        "Laser Middle Management",
        "Electro House",
        "Buzzsaw synths, stomping festival drums, and a corporate countdown exploding into a filthy electro-house drop.",
        (
            "Quarterly drop in three, two, one!",
            "Your metrics stay zero if your morning never runs.",
            "Wake up, hands up, make the dashboard glow.",
            "The beat makes motion and motion makes dough!",
        ),
    ),
    ExpansionTrack(
        "Mainstage Mortgage",
        "Pyrotechnic Escrow",
        "Big Room EDM",
        "Enormous festival kicks, horn blasts, snare-roll suspense, and a ridiculous crowd hook about paying the mortgage.",
        (
            "This is your mainstage mortgage alarm!",
            "Raise both hands if the bank wants money!",
            "Wake up, build up, jump on the one.",
            "No house gets paid while you hide from the sun!",
        ),
    ),
    ExpansionTrack(
        "Eyes Open Forever",
        "Euphoric Deadline",
        "Trance",
        "Galloping trance bass, cathedral pads, ecstatic arpeggios, and a radiant hook lifting wakefulness into the clouds.",
        (
            "Eyes open forever, carried by the dawn.",
            "The dream becomes real when the dreamer moves on.",
            "Run through the light, let the old sleep sever.",
            "Awake is the future—eyes open forever!",
        ),
    ),
    ExpansionTrack(
        "Psychedelic Punchclock",
        "Mushroom Accounting",
        "Psytrance",
        "Elastic psytrance bass, alien percussion, spiraling leads, and a deadpan voice guiding workers through a cosmic punchclock.",
        (
            "Observe the pillow: it is not legal tender.",
            "Observe the clock: it has eaten your morning.",
            "Breathe in, stand up, enter the spiral.",
            "Cosmic or corporate, awake means survival!",
        ),
    ),
    ExpansionTrack(
        "Office Slut O'Clock",
        "Patent Leather Labor",
        "Electroclash",
        "Female-led electroclash with icy synths, dirty bass, and a glamorous consensual slut-pride monologue for grown professionals.",
        (
            "It's office slut o'clock; yes, I'm grown and enthusiastic.",
            "My consent is explicit and my spreadsheet fantastic.",
            "Boots, brains, boundaries, bills.",
            "I own the room before breakfast, darling!",
        ),
        True,
    ),
    ExpansionTrack(
        "Chrome Dawn Driver",
        "VHS Overtime",
        "Synthwave",
        "Neon arpeggios, gated drums, overdriven guitar, and a cinematic driver racing a payroll deadline toward sunrise.",
        (
            "Chrome dawn driver, ignition in your chest.",
            "The highway pays the moving, not the comfortably dressed.",
            "Turn the key, burn the fog, outrun delay.",
            "Neon eyes open all the way!",
        ),
    ),
    ExpansionTrack(
        "Brass Knuckles at Breakfast",
        "The Unionized Horns",
        "Big Band",
        "A ferocious swing orchestra with screaming trumpets, walking bass, explosive toms, and a bandleader roasting the late sleeper.",
        (
            "Good morning, deadbeat, the brass section is billing by the bar!",
            "Your coffee is cold and your competition is hot.",
            "Swing out of bed, punch in on two and four.",
            "Awake cats earn; sleepy cats snore!",
        ),
    ),
    ExpansionTrack(
        "Sousaphone Foreclosure",
        "Second Line Collections",
        "Brass Band",
        "New Orleans second-line drums, sousaphone bass, and jubilant horns parading a foreclosure notice through the bedroom.",
        (
            "Second line sunrise coming down your hall.",
            "Sousaphone says the bank just called.",
            "Dance out the doorway, put your work shoes on.",
            "Brass wakes the broke and carries them on!",
        ),
    ),
    ExpansionTrack(
        "Pick It Up, Deadbeat",
        "Checkered Paystub",
        "Ska",
        "Hyperactive upstroke guitar, bouncing bass, bright horns, and a rude two-tone call-and-response about getting vertical.",
        (
            "Pick it up, pick it up, pick your deadbeat ass up!",
            "The horn line works harder than your whole excuse.",
            "Skank to the kitchen, sprint to the train.",
            "Awake on the offbeat, paid on the one!",
        ),
    ),
    ExpansionTrack(
        "Skank, Slut, Invoice",
        "Fishnet Timecard",
        "Ska Punk",
        "Female-led ska punk with breakneck upstrokes, gang horns, and a jubilant adult slut-pride chorus grounded in consent.",
        (
            "Skank, slut, invoice—my morning, my rules!",
            "Consenting grown lovers and paid-up tools.",
            "I choose my pleasure, I choose my grind.",
            "Fishnets on, boundaries strong, money on my mind!",
        ),
        True,
    ),
    ExpansionTrack(
        "Rocksteady Revenue",
        "Dawn Sound System",
        "Rocksteady",
        "Warm organ bubbles and heavy one-drop bass pushed unusually hard beneath a smooth warning about wasting the cool morning.",
        (
            "Easy now, sleeper, but easy does not mean still.",
            "The sun keeps moving and so must your will.",
            "Roll from the covers, settle into stride.",
            "Awake keeps rhythm and money beside!",
        ),
    ),
    ExpansionTrack(
        "Coffin Pompadour",
        "Upright Vandal",
        "Psychobilly",
        "Slap-bass frenzy, horror-movie guitar twang, and a manic singer dragging a pompadoured corpse out of bed.",
        (
            "Comb that coffin pompadour, zombie, dawn is here!",
            "Your paycheck fled the graveyard screaming.",
            "Slap the bass, slap awake, run wild downtown.",
            "Dead in bed or alive getting paid—choose now!",
        ),
    ),
    ExpansionTrack(
        "Grease the Alarm",
        "Hot Rod Timesheet",
        "Rockabilly",
        "Upright bass slaps, hot-rod guitar, handclaps, and a pomade-slick vocalist racing the clock to a blue-collar shift.",
        (
            "Grease the alarm, fire up the shoes.",
            "That mattress motor only runs on lose.",
            "Comb it high, shift it hard, peel into day.",
            "The hot rod worker gets hot rod pay!",
        ),
    ),
    ExpansionTrack(
        "Tidal Wave Timesheet",
        "Reverb Foreman",
        "Surf Punk",
        "Machine-gun surf guitar, floor-tom waves, and shouted punk vocals riding a timesheet like a stolen longboard.",
        (
            "Tidal wave timesheet, paddle out now!",
            "You cannot surf daylight face-down in a towel.",
            "Stand on the board, cut through delay.",
            "Ride the clock hard and get fucking paid!",
        ),
    ),
    ExpansionTrack(
        "Boots, Coffee, Trouble",
        "The Overtime Rustlers",
        "Cowpunk",
        "Telecaster twang at punk velocity, galloping snare, and a whiskey-rough posse chasing a sleeper off the ranch.",
        (
            "Boots, coffee, trouble—the breakfast of the paid.",
            "Your horse left early while you cuddled in the shade.",
            "Saddle the morning, rope every chore.",
            "No gold in the bunkhouse, now hit the door!",
        ),
    ),
    ExpansionTrack(
        "Bagpipe Bonus",
        "The Fiscal Bastards",
        "Celtic Punk",
        "Charging bagpipes, mandolin chop, distorted guitars, and a pub gang turning a quarterly bonus into a dawn battle cry.",
        (
            "Bagpipe bonus, daylight raid!",
            "Raise up the cup to the work getting paid.",
            "Kick off the quilt, march into town.",
            "The morning belongs to the bastards not down!",
        ),
    ),
    ExpansionTrack(
        "Disco Slut Dividend",
        "Consent Mirrorball",
        "Disco",
        "Female-led orchestral disco with relentless four-on-the-floor, strings, and a sparkling consensual slut-pride refrain.",
        (
            "Disco slut dividend, pleasure compounds at dawn.",
            "Every grown lover had consent all night long.",
            "Sequins, agency, paychecks, light.",
            "I own my choices and the dance floor tonight!",
        ),
        True,
    ),
    ExpansionTrack(
        "Strobe Light Salary",
        "Midnight Payroll Express",
        "Hi NRG",
        "Breathless Hi-NRG bass, laser arpeggios, and diva vocals carrying last night's dance floor directly into workday sunrise.",
        (
            "Strobe light salary, neon overtime.",
            "I danced through midnight and still beat the chime.",
            "Eyes bright, pulse high, run into the day.",
            "Energy earns when excuses decay!",
        ),
    ),
    ExpansionTrack(
        "Funk the Forecast",
        "Pocket Revenue Service",
        "Funk",
        "Rubber-band bass, chicken-scratch guitar, horn punches, and a charismatic bandleader putting the forecast deep in the pocket.",
        (
            "Forecast says one hundred percent chance of get up.",
            "Your pocket stays empty when your body stays tucked.",
            "Slide to the coffee, strut to the plan.",
            "Funk makes motion and motion makes bands!",
        ),
    ),
    ExpansionTrack(
        "Slap Bass Layoff",
        "Human Capital Sausage",
        "Funk Metal",
        "Mutant slap bass, chainsaw guitars, rapid-fire rap, and a chorus firing sleep for gross incompetence.",
        (
            "Sleep, you're fired—pack your shit and leave!",
            "You falsified the hours and embezzled my dreams.",
            "Slap that bass, slap awake, hire the day.",
            "My spine is management and management gets paid!",
        ),
    ),
    ExpansionTrack(
        "Bad Bitch Day Shift",
        "Golden Consent Union",
        "Afrobeat",
        "Female-led Afrobeat with interlocking guitars, blazing horns, and a joyful adult slut-pride hook about agency and ambition.",
        (
            "Bad bitch day shift, grown and choosing joy.",
            "My yes is mine to give; my no is not a toy.",
            "Waist moving, work moving, sunrise in command.",
            "Proud slut, bright mind, money in my hand!",
        ),
        True,
    ),
    ExpansionTrack(
        "Salsa the Snooze",
        "Clave Collections",
        "Salsa Punk",
        "Blazing clave, brass, piano montuno, and punk guitar shove a bilingual-flavored wake-up chant across the kitchen floor.",
        (
            "Salsa the snooze, throw the blanket away!",
            "Mueve los pies, own the fucking day!",
            "Clave in the bloodstream, coffee in the cup.",
            "No dinero in the pillow—arriba, get up!",
        ),
    ),
    ExpansionTrack(
        "Promiscuous Polyrhythm",
        "Free Consent Quartet",
        "Free Jazz",
        "Female-led free jazz detonates saxophone clusters and polyrhythms beneath a witty, consensual slut-pride spoken performance.",
        (
            "My rhythm is promiscuous; every entrance is invited.",
            "These grown players listen, consent, and stay delighted.",
            "I improvise pleasure, boundaries, and pay.",
            "This slut wakes early to redefine the day!",
        ),
        True,
    ),
    ExpansionTrack(
        "Alarm Without a Key",
        "No Chord Changes Approved",
        "Experimental Jazz",
        "Prepared piano, splintered drums, multiphonic reeds, and a stern narrator treating wakefulness as an unsolved composition.",
        (
            "The alarm has no key and your bed has no tempo.",
            "Time improvises past your closed eyes.",
            "Enter on one—or enter wherever—but enter.",
            "Awake is the only note that pays!",
        ),
    ),
    ExpansionTrack(
        "Bebop Before Boss",
        "The Five-Thirty Changes",
        "Bebop",
        "Blistering ride cymbal, walking bass, impossible horn lines, and rapid scat roasting anyone whose boss wakes first.",
        (
            "Bebop before boss, changes before chains.",
            "Your pillow plays one chord and drains your brain.",
            "Catch the head, chase the bridge, land the pay.",
            "Wake cats improvise the better day!",
        ),
    ),
    ExpansionTrack(
        "Fusion Fiscal Year",
        "Mahavishnu Accounting Error",
        "Jazz Fusion",
        "Overdriven electric piano, odd-meter bass, shredding guitar, and fusion fireworks compress a fiscal year into one wake cycle.",
        (
            "Fiscal year fusion, nineteen over eight.",
            "Complex time still notices when you are late.",
            "Plug in the brain, solo through the fog.",
            "Awake gets dividends; sleep gets analog!",
        ),
    ),
    ExpansionTrack(
        "Horn Section Hostility",
        "Brass Tax Audit",
        "Brasscore",
        "Hardcore breakdowns collide with a full hostile horn section and a trombone glissando built to remove blankets.",
        (
            "Horn section hostility coming through the wall!",
            "Trombone found the timesheet, trumpet made the call.",
            "Break down the bed frame, upstroke the day.",
            "Brasscore awake and brutally paid!",
        ),
    ),
    ExpansionTrack(
        "March of the Unpaid",
        "Overtime Battalion",
        "Marching Band",
        "Massed brass, piccolo shrieks, bass-drum thunder, and a drill sergeant marching the unpaid directly toward breakfast.",
        (
            "Left, right, wake, work—march of the unpaid!",
            "Your blanket went AWOL, your courage overstayed.",
            "Dress the line, face the light, cadence through the door.",
            "Every step awake is worth one minute more!",
        ),
    ),
    ExpansionTrack(
        "Snare Line Summons",
        "Flam Paradiddle LLC",
        "Drumline",
        "A battery of snares, quads, cymbals, and bass drums executes a precision summons with no harmonic mercy.",
        (
            "This is your snare line summons—appear awake!",
            "Flam every excuse until the bed frame breaks.",
            "Stick heights up, feet timed, coffee in formation.",
            "Drumline discipline funds the operation!",
        ),
    ),
    ExpansionTrack(
        "Testify, Then Timesheet",
        "The Direct Deposit Choir",
        "Gospel Shout",
        "Hammond organ, tambourines, handclaps, and a roof-raising choir testifying that wakefulness beats the graveyard of excuses.",
        (
            "Can I get awake? Awake! Can I get paid? Get paid!",
            "The morning made a way while the lazy delayed.",
            "Testify, stand high, put your hands to the plan.",
            "No blessing hides underneath that divan!",
        ),
    ),
    ExpansionTrack(
        "Slut Alarm Deluxe",
        "Boundary Glitter",
        "Hyperpop",
        "Female-led hyperpop explodes in pitched synths and candy-coated distortion around an explicit, consensual adult slut-pride hook.",
        (
            "Slut alarm deluxe—I'm an adult with standards!",
            "My yes is electric; my no fucking matters.",
            "Cute, awake, consensual, paid.",
            "I own every choice and the noise that I made!",
        ),
        True,
    ),
    ExpansionTrack(
        "Eight-Bit Eviction",
        "Cartridge Payroll",
        "Chiptune Punk",
        "Overclocked game-console leads, live punk drums, and a pixelated gang vocal evicting sleep one power-up at a time.",
        (
            "Press start, deadbeat, your free life is gone.",
            "The sleep boss won while the screen stayed on.",
            "Grab one coffee, gain one spine.",
            "Awake unlocked—now collect your coins!",
        ),
    ),
    ExpansionTrack(
        "Glitch the Grind",
        "Buffering Executive",
        "Glitch Hop",
        "Lurching swung drums, chopped bass, corrupted vocal edits, and a hook rebooting a worker stuck at zero percent.",
        (
            "Buffering ambition at zero percent.",
            "Your bed stole bandwidth and your whole morning went.",
            "Glitch the grind, hard reset the head.",
            "Reconnect to daylight and download bread!",
        ),
    ),
    ExpansionTrack(
        "Body Clock Command",
        "Leather Metrics",
        "EBM",
        "Rigid sequencers, stomping electronic body music, and a leather-clad command vocal ordering limbs back online.",
        (
            "Body clock command: left foot, right foot, rise.",
            "Metrics detect weakness behind both eyes.",
            "Stomp through the kitchen, synchronize pay.",
            "Electronic bodies execute day!",
        ),
    ),
    ExpansionTrack(
        "Factory Dance Citation",
        "Hazard Pay Romance",
        "Industrial Dance",
        "Grinding samples and club drums issue a factory-floor citation while a seductive machine voice counts lost minutes.",
        (
            "Citation one: excessive sleep in a revenue zone.",
            "Citation two: leaving your ambition alone.",
            "Dance to compliance, sparks in your stride.",
            "The factory is awake and the doors are wide!",
        ),
    ),
    ExpansionTrack(
        "Laptop Through the Mattress",
        "Modem Fist Collective",
        "Digital Hardcore",
        "Breakbeats at riot speed, bit-crushed noise, and political screaming threaten the mattress with obsolete electronics.",
        (
            "Laptop through the mattress, modem through the lie!",
            "Algorithms profit while your useful minutes die.",
            "Wake, resist, create, collect.",
            "Digital hardcore has no snooze effect!",
        ),
    ),
    ExpansionTrack(
        "Consentida e Cobrando",
        "Favela Invoice Queen",
        "Baile Funk",
        "Female-led baile funk with tamborzão drums and an adult consensual slut-pride chant celebrating choice, work, and pleasure.",
        (
            "Consenting and charging, I wake when I choose.",
            "Grown, loud, desired—I have nothing to lose.",
            "My body, my baile, my rate, my say.",
            "This proud slut owns the beat and the day!",
        ),
        True,
    ),
    ExpansionTrack(
        "Kuduro Clockout",
        "Luanda Overtime",
        "Kuduro",
        "Frenetic Angolan-inspired percussion, stabbing synth brass, and a commanding dance vocal kicking the bedroom door open.",
        (
            "Kuduro clockout from the kingdom of sleep.",
            "Move so hard that the lost hours leap.",
            "Shoulders, feet, coffee, plan.",
            "Dance into daylight and earn what you can!",
        ),
    ),
    ExpansionTrack(
        "Footwork Forecast",
        "Chicago Minute Market",
        "Footwork",
        "Hyperkinetic kicks, chopped soul commands, and sub-bass make every wasted second dodge between dancing feet.",
        (
            "Footwork forecast: one hundred eighty chances a minute.",
            "Your bed has no future and your feet are not in it.",
            "Cut left, cut right, leave sleep behind.",
            "Fast feet wake a fast-paid mind!",
        ),
    ),
    ExpansionTrack(
        "Bounce Check Breakfast",
        "NOLA Cash Advance",
        "Bounce",
        "New Orleans bounce triggers, brass flashes, and relentless call-and-response turn a bounced check into breakfast cardio.",
        (
            "Where your check at? Bounced! Where your ass at? Bed!",
            "Then bounce from the mattress and go get bread!",
            "Shake for the schedule, work for the win.",
            "Wake up, back it up, begin again!",
        ),
    ),
    ExpansionTrack(
        "Charleston Collections",
        "The Syncopated Bailiffs",
        "Electro Swing",
        "Vintage brass and clarinet samples collide with club kicks and a theatrical bailiff repossessing the sleeper's morning.",
        (
            "Charleston collections, we're repossessing your nap!",
            "The clarinet has evidence, the kick drum has a map.",
            "Swing out, sign here, dance into pay.",
            "The future wears spats and arrives today!",
        ),
    ),
    ExpansionTrack(
        "Every Genre Hates Your Bed",
        "The Hundredth Alarm",
        "Alarmcore",
        "A maximal collision of thrash riffs, trap bass, techno kicks, ska horns, jazz chaos, disco strings, and one final gang command.",
        (
            "Every genre hates your bed and all one hundred agree.",
            "Sleep had the night; the daylight belongs to me.",
            "Guitars, horns, bass, breaks—every sound says move.",
            "Wake up, stay up, get paid, loop the groove!",
        ),
    ),
)


if len(EXPANSION_TRACKS) != 76:
    raise RuntimeError(f"Expected 76 expansion tracks, found {len(EXPANSION_TRACKS)}")
